export const Categories = [
    "Superpowers (least to most powerful)",
    "Places to start dancing uncontrollably (worst to best place)",
    "Smells (worst to best)",
    "Things to give up for the rest of your life (easiest to hardest)",
    "Thing to have the ability to conjure from thin air (worst to best)",
    "Famous people from weakest to strongest in a fight",
    "Things you could purchase for $10,000 (least to most practical)",
    "Scenarios from least to most annoying",
    "Worst to best reasons to go on a quest",
    "Things that are least to most cute",
    "Worst to best things you could do if you could freeze time",
    "Memes from least to most funny",
    "Things you can poke your finger in from worst to best",
    "Worst to best things to give as a gift",
    "Worst to best things to be able to control with your mind",
    "Things you would do if you saw a ghost from least to most likely",
    "Worst to best places to visit as a tourist",
    "Movie/tv show endings from worst to best",
    "Animal sizes (smallest to largest)",
    "Height of things (shortest to tallest)",
    "Worst to best snack foods",
    "Worst to best advice to give to a child",
    "Activities from least to most fun",
    "Scenarios from least to most cringe/awkward",
    "Worst to best things to put in a smoothie",
    "Clothing items from least to most fashionable",
    "Musical artist or acts from worst to best",
    "Things that would least to most improve your day",
    "Animals and fantasy creatures from least to most cool to have as a pet",
    "Movies and tv shows from least to most likely to make you laugh",
    "Movies or tv show moments from least to most likely to make you cry",
    "Worst to best things to do if you were suddenly transported back to the medieval ages",
    "Desserts or sweets from worst to best",
    "Worst to best superhero names",
    "Fast food menu items from worst to best",
    "Things that would least to most likely scare you",
    "Animals and fantasy creatures you’d most to least likely beat in a fist fight",
    "Fictional characters from weakest to strongest in a fight",
    "Experiences from least to most impactful on someone's life",
    "Worst to best times in history you would travel to if you could time travel",
    "Worst to best things to serve at a 5 star restaurant",
    "Hobbies from least to most interesting",
    "Things you would do if you had a free day to yourself from least to most likely",
    "Things that are easiest to hardest to learn",
    "Worst to best wish you would make if you could make any wish",
    "People from poorest to richest",
    "Worst to best things to do everyday",
    "Worst to best ways to travel 1000 kilometres",
    "Sounds and noises from worst to best",
    "Songs from worst to best",
    "Beverages from worst to best",
    "Fictional worlds or settings you'd least to most like to live in",
    "People you'd least to most want to swap bodies with for a day",
    "People or things you'd least to most want on a deserted island with you",
    "Things to pack for lunch from worst to best",
    "Songs you'd hear at a karaoke night from least to most likely",
    "Worst to best things to write a song about",
    "Animals from most to least common",
    "World records from least to most impressive",
    "Things to put on your resume from least to most impressive",
    "Things you can cook at home from easiest to hardest",
    "Worst to best places to get food in your city",
    "Worst to best person to represent you in a criminal trial",
    "Worst to best things to do at a restaurant",
    "Things you least to most want to happen 10 years from now",
    "Jobs or professions from easiest to hardest",
    "Worst to best excuses for being late to work",
    "Things to do as a group from least to most exciting",
    "Worst to best things to do if you had an audience with the queen",
    "Things that least to most likely indicate someone is old",
    "Things that least to most likely indicate someone is young",
    "Items or things people are least to most likely to own",
    "Worst to best things to do if you are stranded on tropical island",
    "Items from least to most useful in a fight",
    "Worst to best things to make review videos of for a living",
    "Worst to best flavours of ice cream",
    "Worst to best toppings on a pizza",
    "Worst to best people from history to have dinner with",
    "Things to eat for breakfast from worst to best",
    "Worst to best things you would do if you could time travel",
    "Worst to best mottos to live by",
    "Worst to best reasons to pursue a career in medicine",
    "Things you've done in your life from least to most often",
    "Things you least to most want to happen 300 years from now",
    "Worst to best things to happen in a crowded elevator",
    "Worst to best reasons to write a strongly worded letter",
    "Things you least to most want to happen at your wedding",
    "Worst to best things about being a vampire",
    "Worst to best reasons to become a supervillain",
    "Worst to best things to see happen at work",
    "Things you would put in a mansion you were building from least to most practical",
    "Least to most intimidating villains from fiction",
    "Worst to best things to have to wear as your uniform at work",
    "Worst to best things to catch while going fishing",
    "Investments from least to most stable",
    "Worst to best things to carry in your purse",
    "Worse to best things to do if you are a teacher",
    "Things you would do if you were a bird from least to most interesting",
];
