import { library, dom } from "@fortawesome/fontawesome-svg-core";

import { faAddressCard } from "@fortawesome/free-solid-svg-icons/faAddressCard";
import { faAdjust } from "@fortawesome/free-solid-svg-icons/faAdjust";
import { faBars } from "@fortawesome/free-solid-svg-icons/faBars";
import { faBath } from "@fortawesome/free-solid-svg-icons/faBath";
import { faBatteryEmpty } from "@fortawesome/free-solid-svg-icons/faBatteryEmpty";
import { faBatteryFull } from "@fortawesome/free-solid-svg-icons/faBatteryFull";
import { faBatteryHalf } from "@fortawesome/free-solid-svg-icons/faBatteryHalf";
import { faBatteryQuarter } from "@fortawesome/free-solid-svg-icons/faBatteryQuarter";
import { faBed } from "@fortawesome/free-solid-svg-icons/faBed";
import { faBeer } from "@fortawesome/free-solid-svg-icons/faBeer";
import { faBicycle } from "@fortawesome/free-solid-svg-icons/faBicycle";
import { faBinoculars } from "@fortawesome/free-solid-svg-icons/faBinoculars";
import { faBirthdayCake } from "@fortawesome/free-solid-svg-icons/faBirthdayCake";
import { faBlind } from "@fortawesome/free-solid-svg-icons/faBlind";
import { faBolt } from "@fortawesome/free-solid-svg-icons/faBolt";
import { faBomb } from "@fortawesome/free-solid-svg-icons/faBomb";
import { faBook } from "@fortawesome/free-solid-svg-icons/faBook";
import { faBriefcase } from "@fortawesome/free-solid-svg-icons/faBriefcase";
import { faBug } from "@fortawesome/free-solid-svg-icons/faBug";
import { faBullhorn } from "@fortawesome/free-solid-svg-icons/faBullhorn";
import { faBus } from "@fortawesome/free-solid-svg-icons/faBus";
import { faCalculator } from "@fortawesome/free-solid-svg-icons/faCalculator";
import { faCar } from "@fortawesome/free-solid-svg-icons/faCar";
import { faChartArea } from "@fortawesome/free-solid-svg-icons/faChartArea";
import { faChartLine } from "@fortawesome/free-solid-svg-icons/faChartLine";
import { faChartPie } from "@fortawesome/free-solid-svg-icons/faChartPie";
import { faChevronLeft } from "@fortawesome/free-solid-svg-icons/faChevronLeft";
import { faChevronRight } from "@fortawesome/free-solid-svg-icons/faChevronRight";
import { faCircle } from "@fortawesome/free-solid-svg-icons/faCircle";
import { faCloud } from "@fortawesome/free-solid-svg-icons/faCloud";
import { faCoffee } from "@fortawesome/free-solid-svg-icons/faCoffee";
import { faCog } from "@fortawesome/free-solid-svg-icons/faCog";
import { faCogs } from "@fortawesome/free-solid-svg-icons/faCogs";
import { faCookie } from "@fortawesome/free-solid-svg-icons/faCookie";
import { faCube } from "@fortawesome/free-solid-svg-icons/faCube";
import { faCubes } from "@fortawesome/free-solid-svg-icons/faCubes";
import { faCut } from "@fortawesome/free-solid-svg-icons/faCut";
import { faDesktop } from "@fortawesome/free-solid-svg-icons/faDesktop";
import { faDice } from "@fortawesome/free-solid-svg-icons/faDice";
import { faDna } from "@fortawesome/free-solid-svg-icons/faDna";
import { faDollarSign } from "@fortawesome/free-solid-svg-icons/faDollarSign";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons/faEnvelope";
import { faEraser } from "@fortawesome/free-solid-svg-icons/faEraser";
import { faExclamationTriangle } from "@fortawesome/free-solid-svg-icons/faExclamationTriangle";
import { faFaucet } from "@fortawesome/free-solid-svg-icons/faFaucet";
import { faFax } from "@fortawesome/free-solid-svg-icons/faFax";
import { faFemale } from "@fortawesome/free-solid-svg-icons/faFemale";
import { faFighterJet } from "@fortawesome/free-solid-svg-icons/faFighterJet";
import { faFileSignature } from "@fortawesome/free-solid-svg-icons/faFileSignature";
import { faFire } from "@fortawesome/free-solid-svg-icons/faFire";
import { faFireExtinguisher } from "@fortawesome/free-solid-svg-icons/faFireExtinguisher";
import { faFlag } from "@fortawesome/free-solid-svg-icons/faFlag";
import { faFlask } from "@fortawesome/free-solid-svg-icons/faFlask";
import { faFutbol } from "@fortawesome/free-solid-svg-icons/faFutbol";
import { faGamepad } from "@fortawesome/free-solid-svg-icons/faGamepad";
import { faGift } from "@fortawesome/free-solid-svg-icons/faGift";
import { faGrin } from "@fortawesome/free-solid-svg-icons/faGrin";
import { faHandPeace } from "@fortawesome/free-solid-svg-icons/faHandPeace";
import { faHandSpock } from "@fortawesome/free-solid-svg-icons/faHandSpock";
import { faHashtag } from "@fortawesome/free-solid-svg-icons/faHashtag";
import { faHistory } from "@fortawesome/free-solid-svg-icons/faHistory";
import { faHome } from "@fortawesome/free-solid-svg-icons/faHome";
import { faHotel } from "@fortawesome/free-solid-svg-icons/faHotel";
import { faHourglass } from "@fortawesome/free-solid-svg-icons/faHourglass";
import { faHourglassEnd } from "@fortawesome/free-solid-svg-icons/faHourglassEnd";
import { faHourglassHalf } from "@fortawesome/free-solid-svg-icons/faHourglassHalf";
import { faIdBadge } from "@fortawesome/free-solid-svg-icons/faIdBadge";
import { faIdCard } from "@fortawesome/free-solid-svg-icons/faIdCard";
import { faLanguage } from "@fortawesome/free-solid-svg-icons/faLanguage";
import { faList } from "@fortawesome/free-solid-svg-icons/faList";
import { faMale } from "@fortawesome/free-solid-svg-icons/faMale";
import { faMap } from "@fortawesome/free-solid-svg-icons/faMap";
import { faMapSigns } from "@fortawesome/free-solid-svg-icons/faMapSigns";
import { faMicrochip } from "@fortawesome/free-solid-svg-icons/faMicrochip";
import { faMoneyBill } from "@fortawesome/free-solid-svg-icons/faMoneyBill";
import { faMortarPestle } from "@fortawesome/free-solid-svg-icons/faMortarPestle";
import { faPaw } from "@fortawesome/free-solid-svg-icons/faPaw";
import { faPen } from "@fortawesome/free-solid-svg-icons/faPen";
import { faPencilAlt } from "@fortawesome/free-solid-svg-icons/faPencilAlt";
import { faPhone } from "@fortawesome/free-solid-svg-icons/faPhone";
import { faPhoneSlash } from "@fortawesome/free-solid-svg-icons/faPhoneSlash";
import { faPlug } from "@fortawesome/free-solid-svg-icons/faPlug";
import { faPlusCircle } from "@fortawesome/free-solid-svg-icons/faPlusCircle";
import { faPowerOff } from "@fortawesome/free-solid-svg-icons/faPowerOff";
import { faQuestionCircle } from "@fortawesome/free-solid-svg-icons/faQuestionCircle";
import { faQuoteLeft } from "@fortawesome/free-solid-svg-icons/faQuoteLeft";
import { faSatelliteDish } from "@fortawesome/free-solid-svg-icons/faSatelliteDish";
import { faShip } from "@fortawesome/free-solid-svg-icons/faShip";
import { faSignLanguage } from "@fortawesome/free-solid-svg-icons/faSignLanguage";
import { faSitemap } from "@fortawesome/free-solid-svg-icons/faSitemap";
import { faSpaceShuttle } from "@fortawesome/free-solid-svg-icons/faSpaceShuttle";
import { faStreetView } from "@fortawesome/free-solid-svg-icons/faStreetView";
import { faTags } from "@fortawesome/free-solid-svg-icons/faTags";
import { faThermometerEmpty } from "@fortawesome/free-solid-svg-icons/faThermometerEmpty";
import { faTicketAlt } from "@fortawesome/free-solid-svg-icons/faTicketAlt";
import { faTrash } from "@fortawesome/free-solid-svg-icons/faTrash";
import { faTree } from "@fortawesome/free-solid-svg-icons/faTree";
import { faUmbrella } from "@fortawesome/free-solid-svg-icons/faUmbrella";
import { faUnlock } from "@fortawesome/free-solid-svg-icons/faUnlock";
import { faUserCircle } from "@fortawesome/free-solid-svg-icons/faUserCircle";
import { faUsers } from "@fortawesome/free-solid-svg-icons/faUsers";
import { faWrench } from "@fortawesome/free-solid-svg-icons/faWrench";

import { faTelegram } from "@fortawesome/free-brands-svg-icons/faTelegram";
import { faImdb } from "@fortawesome/free-brands-svg-icons/faImdb";
import { faEtsy } from "@fortawesome/free-brands-svg-icons/faEtsy";
import { faApple } from "@fortawesome/free-brands-svg-icons/faApple";
import { faAmazon } from "@fortawesome/free-brands-svg-icons/faAmazon";
import { faQuora } from "@fortawesome/free-brands-svg-icons/faQuora";
import { faWindows } from "@fortawesome/free-brands-svg-icons/faWindows";
import { faFacebookSquare } from "@fortawesome/free-brands-svg-icons/faFacebookSquare";
import { faTwitter } from "@fortawesome/free-brands-svg-icons/faTwitter";
import { faGoogle } from "@fortawesome/free-brands-svg-icons/faGoogle";
import { faAndroid } from "@fortawesome/free-brands-svg-icons/faAndroid";
import { faLinux } from "@fortawesome/free-brands-svg-icons/faLinux";

library.add(faAddressCard);
library.add(faAdjust);
library.add(faBars);
library.add(faBath);
library.add(faBatteryEmpty);
library.add(faBatteryFull);
library.add(faBatteryHalf);
library.add(faBatteryQuarter);
library.add(faBed);
library.add(faBeer);
library.add(faBicycle);
library.add(faBinoculars);
library.add(faBirthdayCake);
library.add(faBlind);
library.add(faBolt);
library.add(faBomb);
library.add(faBook);
library.add(faBriefcase);
library.add(faBug);
library.add(faBullhorn);
library.add(faBus);
library.add(faCalculator);
library.add(faCar);
library.add(faChartArea);
library.add(faChartLine);
library.add(faChartPie);
library.add(faChevronLeft);
library.add(faChevronRight);
library.add(faCircle);
library.add(faCloud);
library.add(faCoffee);
library.add(faCog);
library.add(faCogs);
library.add(faCookie);
library.add(faCube);
library.add(faCubes);
library.add(faCut);
library.add(faDesktop);
library.add(faDice);
library.add(faDna);
library.add(faDollarSign);
library.add(faEnvelope);
library.add(faEraser);
library.add(faExclamationTriangle);
library.add(faFaucet);
library.add(faFax);
library.add(faFemale);
library.add(faFighterJet);
library.add(faFileSignature);
library.add(faFire);
library.add(faFireExtinguisher);
library.add(faFlag);
library.add(faFlask);
library.add(faFutbol);
library.add(faGamepad);
library.add(faGift);
library.add(faGrin);
library.add(faHandPeace);
library.add(faHandSpock);
library.add(faHashtag);
library.add(faHistory);
library.add(faHome);
library.add(faHotel);
library.add(faHourglass);
library.add(faHourglassEnd);
library.add(faHourglassHalf);
library.add(faIdBadge);
library.add(faIdCard);
library.add(faLanguage);
library.add(faList);
library.add(faMale);
library.add(faMap);
library.add(faMapSigns);
library.add(faMicrochip);
library.add(faMoneyBill);
library.add(faMortarPestle);
library.add(faPaw);
library.add(faPen);
library.add(faPencilAlt);
library.add(faPhone);
library.add(faPhoneSlash);
library.add(faPlug);
library.add(faPlusCircle);
library.add(faPowerOff);
library.add(faQuestionCircle);
library.add(faQuoteLeft);
library.add(faSatelliteDish);
library.add(faShip);
library.add(faSignLanguage);
library.add(faSitemap);
library.add(faSpaceShuttle);
library.add(faStreetView);
library.add(faTags);
library.add(faThermometerEmpty);
library.add(faTicketAlt);
library.add(faTrash);
library.add(faTree);
library.add(faUmbrella);
library.add(faUnlock);
library.add(faUserCircle);
library.add(faUsers);
library.add(faWrench);
library.add(faTelegram);
library.add(faImdb);
library.add(faEtsy);
library.add(faApple);
library.add(faAmazon);
library.add(faQuora);
library.add(faWindows);
library.add(faFacebookSquare);
library.add(faTwitter);
library.add(faGoogle);
library.add(faAndroid);
library.add(faLinux);

dom.watch();
