export const WordPairs = [
    ['Chicken', 'KFC'],
    ['Charcoal', 'Fuel'],
    ['Bill Clinton', 'Barack Obama'],
    ['Kim Jong-un', 'Adolf Hitler'],
    ['Hipster', 'Hippie'],
    ['Laptop', 'Notebook'],
    ['Abstract', 'Philosophical'],
    ['Butter', 'Jam'],
    ['Break', 'Destroy'],
    ['Clean', 'Tidy'],
    ['Cup', 'Bowl'],
    ['Dance', 'Twirl'],
    ['Dead', 'Unconscious'],
    ['Laughter', 'Funny'],
    ['Bone', 'Skeleton'],
    ['Duke', 'Viscount'],
    ['Fast', 'Speeding'],
    ['Soda', 'Tap water'],
    ['Fish', 'Prawn'],
    ['Alert', 'Warning'],
    ['Chips', 'Snacks'],
    ['Float', 'Drift'],
    ['Heavy', 'Dense'],
    ['Stranded', 'Lost'],
    ['Food', 'Nutrients'],
    ['Freeze', 'Cold'],
    ['Freeze', 'Ice'],
    ['Cold', 'Ice'],
    ['Wax', 'Candle'],
    ['Flame', 'Hot'],
    ['Fire', 'Hot'],
    ['Singer', 'Actor'],
    ['Rotten', 'Stale'],
    ['Dew', 'Droplets'],
    ['Intelligence', 'Wisdom'],
    ['Power', 'Authority'],
    ['Grow', 'Big'],
    ['Horse', 'Pony'],
    ['Cart', 'Carriage'],
    ['Rap Music', 'Death Metal'],
    ['RocknRoll', 'Disco'],
    ['Rock Band', 'Boy Band'],
    ['Sorbet', 'Ice-cream'],
    ['King', 'President'],
    ['Ruler', 'Measuring Tape'],
    ['Knife', 'Sword'],
    ['Dagger', 'Knife'],
    ['Dagger', 'Sword'],
    ['Blade', 'Knife'],
    ['Mining', 'Drilling'],
    ['Boring', 'Uninteresting'],
    ['Dull', 'Uninteresting'],
    ['Laugh', 'Comedy'],
    ['Worm', 'Pest'],
    ['Letters', 'Alphabet'],
    ['Planets', 'Stars'],
    ['Sunny', 'Hot'],
    ['Emptiness', 'Vacuum'],
    ['Silence', 'Quiet'],
    ['Peace', 'Calm'],
    ['Paint', 'Paintbrush'],
    ['Pencil', 'Pen'],
    ['Peaches', 'Cream'],
    ['Pen', 'Ink'],
    ['Business', 'Work'],
    ['Magazine', 'Newspaper'],
    ['Rich', 'Spendthrift'],
    ['Poor', 'Thrifty'],
    ['Human Rights', 'Justice'],
    ['Human Rights', 'Equality'],
    ['Snow', 'Ice'],
    ['Assets', 'Bank Account'],
    ['Spongecake', 'Custard'],
    ['Strawberries', 'Raspberries'],
    ['Wind', 'Blow'],
    ['Storm', 'Gale'],
    ['Hurricane', 'Typoon'],
    ['Neptune', 'Jupiter'],
    ['Furry', 'Warm and Fuzzy'],
    ['Cushion', 'Pillow'],
    ['Cookie', 'Biscuit'],
    ['Cookie', 'Oreo'],
    ['Coffeebean', 'Cocoa'],
    ['Thunder', 'Lightning'],
    ['Mountain', 'Hill'],
    ['Hiking', 'Mountain Climbing'],
    ['Hiking', 'Trekking'],
    ['Toothpaste', 'Toothbrush'],
    ['War', 'Riot'],
    ['War', 'Battle'],
    ['Rebellion', 'Riot'],
    ['Protest', 'Riot'],
    ['Fan', 'Aircon'],
    ['Thermostat', 'Aircon'],
    ['Under', 'Below'],
    ['Walk', 'Run'],
    ['Walk', 'Hike'],
    ['Wet', 'Slippery'],
    ['Greasy', 'Slippery'],
    ['Greasy', 'Oily'],
    ['Wine', 'Beer'],
    ['Witchcraft', 'Wizardry'],
    ['Witchcraft', 'Magic'],
    ['Illusion', 'Imagination'],
    ['Magician', 'Clown'],
    ['Comedian', 'Clown'],
    ['Magician', 'Illusionist'],
    ['Musical', 'Movie'],
    ['Musical', 'Theatre'],
    ['Anime', 'Cartoon'],
    ['Anime', 'Manga'],
    ['Moonlight', 'Twilight'],
    ['Werewolves', 'Monsters'],
    ['Monsters', 'Beasts'],
    ['Jellyfish', 'Sea Cucumber'],
    ['Darkness', 'Void'],
    ['Darkness', 'Emptiness'],
    ['Blank', 'Emptiness'],
    ['Blank', 'Void'],
    ['Worship', 'Pray'],
    ['Noisy', 'Exuberant'],
    ['Drummer', 'Guitarist'],
    ['Kettle', 'Pot'],
    ['Watch', 'Clock'],
    ['Dumbbell', 'Barbell'],
    ['Butt', 'Ass'],
    ['Donkey', 'Pony'],
    ['Hopeful', 'Optimistic'],
    ['Skeptical', 'Cynical'],
    ['First', 'Second'],
    ['Noob', 'Loser'],
    ['Coat', 'Sweater'],
    ['Coat', 'Jacket'],
    ['Windbreaker', 'Jacket'],
    ['Sweater', 'Jacket'],
    ['Dry', 'Dehydrated'],
    ['Humid', 'Sweaty'],
    ['Humid', 'Hot'],
    ['Smooth', 'Slippery'],
    ['Analog', 'Mechanical'],
    ['Bag', 'Purse'],
    ['Purse', 'Wallet'],
    ['Cushion', 'Polster'],
    ['Bedsheet', 'Comforter'],
    ['Hygienic', 'Sterile'],
    ['Bridge', 'Poker'],
    ['Gambling', 'Betting'],
    ['Calm', 'Zen'],
    ['Peaceful', 'Zen'],
    ['Despair', 'Sadness'],
    ['Despair', 'Anguish'],
    ['Exhausted', 'Tired'],
    ['Rude', 'Clueless'],
    ['Wise', 'Experienced'],
    ['Wisdom', 'Experience'],
    ['Moisture', 'Dew'],
    ['Moisture', 'Condensation'],
    ['Speed', 'Dexterity'],
    ['Agility', 'Dexterity'],
    ['Atheletic', 'Fit'],
    ['Healthy', 'Fit'],
    ['Reflection', 'Mirror'],
    ['Polka dots', 'Pattern'],
    ['Polka dots', 'Hearts'],
    ['Guitar', 'Ukulele'],
    ['Orchestra', 'Ensemble'],
    ['Choir', 'Ensemble'],
    ['Choir', 'Acapella'],
    ['Violin', 'Viola'],
    ['Quarter', 'Dime'],
    ['Coin', 'Dime'],
    ['Chilli', 'Wasabi'],
    ['Chilli', 'Pepper'],
    ['Sushi', 'Sashimi'],
    ['Movement', 'Motion'],
    ['Velocity', 'Motion'],
    ['Speed', 'Motion'],
    ['Dull', 'Boring'],
    ['Excited', 'Enthusiatic'],
    ['Control', 'Treatment'],
    ['Gun', 'Pistol'],
    ['Twilight', 'Dusk'],
    ['Dusk', 'Sunset'],
    ['Dusk', 'Night'],
    ['Chair', 'Bench'],
    ['Exuberant', 'Happy'],
    ['Exuberant', 'Excited'],
    ['Pot', 'Pan'],
    ['Alarm', 'Timer'],
    ['Bench Press Machine', 'Treadmill'],
    ['Genuine', 'Real'],
    ['Hopeful', 'Wishful'],
    ['Optimistic', 'Confident'],
    ['First', 'Top'],
    ['Heated', 'Warmed'],
    ['Purse', 'Hangbag'],
    ['Bolster', 'Pillow'],
    ['Bedsheet', 'Blanket'],
    ['Unhygienic', 'Filty'],
    ['Bacteria', 'Virus'],
    ['Virus', 'Contaminated'],
    ['Poison', 'Contaminated'],
    ['Poison', 'Venom'],
    ['Poison', 'Toxic'],
    ['Filthy', 'Smelly'],
    ['Pungent', 'Smelly'],
    ['Poker', 'Cards'],
    ['Sadness', 'Despair'],
    ['Sadness', 'Gloom'],
    ['Clueless', 'Lost'],
    ['Experienced', 'Professional'],
    ['Toilet Bowl', 'Urinal'],
    ['Toilet', 'Bathroom'],
    ['Dew', 'Mist'],
    ['Mist', 'Condensation'],
    ['Fog', 'Mist'],
    ['Agile', 'Flexible'],
    ['Agile', 'Swift'],
    ['Hearts', 'Spades'],
    ['Violin', 'Guitar'],
    ['Wasabi', 'Mustard'],
    ['BBQ Sauce', 'Honey Mustard'],
    ['Soy Sauce', 'Vinegar'],
    ['Stationary', 'Still'],
    ['Stationary', 'Motionless'],
    ['Motionless', 'Unconsious'],
    ['Sharp', 'Pointed'],
    ['Cautious', 'Careful'],
    ['Cautious', 'Vigilant'],
    ['Vigilant', 'Attentive'],
    ['Treatment', 'Care'],
    ['Treatment', 'Cure'],
    ['Treatment', 'Medicine'],
    ['Treatment', 'Heal'],
    ['Heal', 'Cure'],
    ['Bow', 'Kneel'],
    ['Pray', 'Kneel'],
    ['Force', 'Coerce'],
    ['Dust', 'Dirt'],
    ['Fog', 'Mist'],
    ['Steam', 'Mist'],
    ['Steam', 'Smoke'],
    ['Vacuum', 'Space'],
    ['Parade', 'Celebration'],
    ['Happy', 'Joy'],
    ['Disgust', 'Dislike'],
    ['Dumbbell', 'Kettle Bell'],
    ['Harry Potter', 'Ron Weasley'],
    ['Authentic', 'Genuine'],
    ['Fake', 'Pirated'],
    ['Contraband', 'Illegal'],
    ['Contraband', 'Pirated'],
    ['Wishful', 'Hopeful'],
    ['Jacket', 'Vest'],
    ['Yogurt', 'Smoothie'],
    ['Analog', 'Manual'],
    ['Stocks', 'Bank Account'],
    ['Hobo', 'Homeless'],
    ['Filthy', 'Rags'],
    ['Peaceful', 'Quiet'],
    ['Despair', 'Desperate'],
    ['Thriftstore', 'Goodwill'],
    ['Factory', 'Industry'],
    ['Factory', 'Workshop'],
    ['Professional', 'Skillful'],
    ['Experienced', 'Skillful'],
    ['Toilet Bowl', 'Basin'],
    ['Water', 'Drink'],
    ['Violin', 'Strings'],
    ['Coin', 'Penny'],
    ['Mustard', 'Ketchup'],
    ['Still', 'Quiet'],
    ['Still', 'Motionless'],
    ['Round', 'Oval'],
    ['Fat', 'Overweight'],
    ['Obese', 'Overweight'],
    ['Kneel', 'Crawl'],
    ['Coerce', 'Persuade'],
    ['Coax', 'Persuade'],
    ['Convince', 'Persuade'],
    ['Sketching','Drawing'],
    ['Drawing','Painting'],
    ['Sketching','Doodling'],
    ['Landscape','Scenery'],
    ['Painting','Mural'],
    ['Crime','Evil'],
    ['Evil','Bad'],
    ['Evil','Corrupt'],
    ['Greed','Corrupt'],
    ['Greedy','Gluttony'],
    ['Hunger','Starvation'],
    ['Hunger','Lust'],
    ['Lust','Greed'],
    ['Lust','Craving'],
    ['Lust','Horny'],
    ['Lust','Longing'],
    ['Belonging','Ownership'],
    ['Nationalistic','Patriotism'],
    ['Racism','Bigotry'],
    ['Bias','Biotry'],
    ['Racism','Sexism'],
    ['Sexism','Bias'],
    ['Unfairness','Discrimination'],
    ['Discrimination','Bias'],
    ['Discrimination','Sexism'],
    ['Morality','Virtue'],
    ['Morality','Values'],
    ['Values','Principles'],
    ['Values','Virtues'],
    ['Values','Morals'],
    ['Honesty','Integrity'],
    ['Integrity','Principles'],
    ['Allegience','Loyalty'],
    ['Devotion','Loyal'],
    ['Obedience','Loyal'],
    ['Obedience','Adherence'],
    ['Cookie monster on the moon', 'Eating peanut button in Mars'],
    ['Walk walk walk fall down', 'Walk walk walk bump into tree'],
    ['6 Disturbing Truths Your Mother Isn\'t Telling You', '20 Shocking Facts Teachers Are Using Against You'],
    ['ROFLMAO','TROLOLOL'],
    ['Infinite Termination','Indefinite End'],
    ['Podcasts are for geeks', 'Watching twitch.tv like a nerd'],
    ['Lonely plumber squating on a toilet', 'Sad electrician taking a piss'],
    ['My worthless date at Kohls', 'Buying junk at at best buy'],
    ['Whispering sweet nothings into her ear', 'Cheesy pick-up lines on Tinder'],
    ['Staring at a text for damn long', 'Getting stuck how to reply on whatsapp'],
    ['Having a Mental conversation about having a mental conversation with oneself', 'Dreaming about myself dreaming about myself'],
    ['Sex positions on the beach', 'Alcoholic beverages with sexual innuendos'],
    ['Getting drunk', 'Getting high'],
    ['Famous last words', 'Famous movie quotes'],
    ['Films with 2 men on its poster', 'Cop-buddy comedy films'],
    ['43','47'],
    ['Photograph', 'Picture'],
    ['Picture', 'Painting'],
    ['Photograph', 'Portrait'],
    ['Photograph', 'Image'],
    ['Whacky monkey in a spaceship', 'Chewbaca acting in star trek'],
    ['Keyboard', 'Typewriter'],
    ['Computing terms based on non-computing objects', 'Things you can find in a house'],
    ['Whiteboard', 'Blackboard'],
    ['Screen', 'Monitor'],
    ['Dragonfruit', 'Passionfruit'],
    ['Biblical characters', 'Common first names'],
    ['Smoking weed', 'Getting drunk'],
    ['Getting laid', 'Netflix and chill'],
    ['Cupcakes', 'Cookies'],
    ['Getting punched in the face', 'Getting kicked in the groin'],
    ['Experiences that involves lots of pain', 'Experiences that are ultimately rewarding'],
    ['Sophisticated sounding quotes', 'Meaningless sayings']
];
